-- Outbox used by the send-pending-emails Edge Function.
create table if not exists public.inbox_entries (
  id              bigint generated by default as identity primary key,
  to_address      text not null,
  from_address    text not null default 'IGASialFarm@gmail.com',
  subject         text not null,
  body            text not null,
  sponsorship_id  text references public.sponsorships(id) on delete set null,
  status          text not null default 'pending'
                  check (status in ('pending', 'sent', 'failed')),
  error_message   text,
  created_at      timestamptz not null default now(),
  sent_at        timestamptz
);

alter table public.inbox_entries
  add column if not exists to_address text,
  add column if not exists from_address text default 'IGASialFarm@gmail.com',
  add column if not exists subject text,
  add column if not exists body text,
  add column if not exists sponsorship_id text,
  add column if not exists status text default 'pending',
  add column if not exists error_message text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists sent_at timestamptz;

create index if not exists inbox_entries_pending_idx
  on public.inbox_entries (created_at)
  where status = 'pending';

alter table public.inbox_entries enable row level security;

drop policy if exists inbox_entries_insert on public.inbox_entries;
create policy inbox_entries_insert on public.inbox_entries
  for insert to anon, authenticated
  with check (status = 'pending');
